server:
  port: 8083

spring:
  application:
    name: loyalty-service
  datasource:
    url: jdbc:postgresql://localhost:5432/retailforge
    username: retailforge
    password: retailforge
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
      data-locations: classpath:seed.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{traceId:-}] %logger{20} - %msg%n"
